[project]
name = 'nexoar'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'STR738QQX1PVTM6WTDF833Z18T8R0ZB791TCNEFM.pyth-oracle-v4'

[[project.requirements]]
contract_id = 'STR738QQX1PVTM6WTDF833Z18T8R0ZB791TCNEFM.pyth-storage-v4'

[[project.requirements]]
contract_id = 'STR738QQX1PVTM6WTDF833Z18T8R0ZB791TCNEFM.pyth-pnau-decoder-v3'

[[project.requirements]]
contract_id = 'STR738QQX1PVTM6WTDF833Z18T8R0ZB791TCNEFM.wormhole-core-v4'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
[contracts.liquidity-manager-v1-4-0]
path = 'contracts/liquidity-manager-v1-4-0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.mock-usda-v1-4-0]
path = 'contracts/mock-usda-v1-4-0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.nexoar-pricing-v1-4-0]
path = 'contracts/nexoar-pricing-v1-4-0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.nexoar-v1-4-0]
path = 'contracts/nexoar-v1-4-0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.vault-tracker-v1-4-0]
path = 'contracts/vault-tracker-v1-4-0.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
