const NEXOAR_CORE_CONTRACT =
  "STWHP9XFF0H1KGMNAE06BYZ59BJRWANFQ5V9QYT6.nexoar-v1-4-0";

const NEXOAR_CORE_CONTRACT_ADDRESS = "STWHP9XFF0H1KGMNAE06BYZ59BJRWANFQ5V9QYT6";
const NEXOAR_CORE_CONTRACT_NAME = "nexoar-v1-4-0";

const HERMES_API_URL = "https://hermes.pyth.network";

export {
  NEXOAR_CORE_CONTRACT,
  NEXOAR_CORE_CONTRACT_ADDRESS,
  NEXOAR_CORE_CONTRACT_NAME,
  HERMES_API_URL,
};
